%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 4 -*-
---

on:
    push:
        branches:
          - 'build-**'
          - 'debug-**'


jobs:
    invoke_remote_donut:
        uses: 'mk-pmb/actions-test-230422/.github/workflows/donut.yaml@bagel'
        with:
            WF_IMPL: 'mk-pmb/actions-test-230422/.github/workflows/donut.yaml@bagel'



...
